{{- $secretInj := ( lookup "v1" "Secret" .Release.Namespace "postgres-connection" ) | default dict}}
{{- $injData := ( get $secretInj "data" ) | default dict }}

{{- $secretObj := ( lookup "v1" "Secret" .Release.Namespace .Values.db.secretKeyRef.name ) | default dict}}
{{- $secretData := ( get $secretObj "data" ) | default dict }}

{{- $user :=  (( get $secretData "POSTGRES_USER" ) | b64dec ) | default "postgres" }}
{{- $sslmode :=  (( get $secretData "SSLMODE" ) | b64dec ) | default "disable"  }}
{{- $password :=  (( get $injData "POSTGRES_PASSWORD") | b64dec ) | default (( get $secretData "POSTGRES_PASSWORD") | b64dec ) | default ( randAlphaNum 32 )  }}
{{- $host := print "postgres." .Release.Namespace  ".svc.cluster.local" }}

{{- $jwtSecretObj := ( lookup "v1" "Secret" .Release.Namespace .Values.db.jwtSecretKeyRef.name ) | default dict}}
{{- $jwtSecretData := ( get $jwtSecretObj "data" ) | default dict }}
{{- $pgrstJWTSecret :=  (( get $jwtSecretData .Values.db.jwtSecretKeyRef.key) | b64dec ) | default (( get $injData "PGRST_JWT_SECRET") | b64dec ) | default ( randAlphaNum 32 ) }}

{{- $kratosSecret := ((lookup "v1" "Secret" .Release.Namespace (include "kratos-im.secretname" .)).data | default dict) -}}
{{- $kratosDSN := ( (get $secretData "DB_URL") | b64dec ) | default "DB_URL" -}}

{{- if .Values.db.create  }}
# Change kratos DSN to generated DB_URL
{{- $kratosDSN = (print "postgres://" $user ":" $password "@" $host "/mission_control")  -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.db.secretKeyRef.name }}
type: Opaque
stringData:
  POSTGRES_USER: {{ $user | quote }}
  POSTGRES_PASSWORD: {{ $password | quote }}
  POSTGRES_HOST: {{ $host | quote }}
  SSLMODE: {{ $sslmode | quote }}
  PGRST_JWT_SECRET: {{ $pgrstJWTSecret | quote }}
  DB_URL:  {{ (print "postgres://" $user ":" $password "@" $host "/mission_control?sslmode=" $sslmode ) | quote }}

{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kratos-im.secretname" . }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  dsn: {{ $kratosDSN | b64enc | quote }}
  # Generate a random secret if the user doesn't give one. User given secret has priority
  secretsDefault: {{ ( include "kratos-im.secrets.default" . | default ((get $kratosSecret "secretsDefault") | b64dec) | default ( randAlphaNum 32 )) | required "Value kratos.config.secrets.default can not be empty!" | b64enc | quote }}
  secretsCookie: {{ ( include "kratos-im.secrets.cookie" . | default ((get $kratosSecret "secretsCookie") | b64dec) | default (randAlphaNum 32) ) | required "Value kratos.config.secrets.cookie can not be empty!" | b64enc | quote }}
  secretsCipher: {{ ( include "kratos-im.secrets.cipher" . | default ((get $kratosSecret "secretsCipher") | b64dec) | default ( randAlphaNum 32 )) | required "Value kratos.config.secrets.cipher can not be empty!" | b64enc | quote }}
  {{- if .Values.kratos.kratos.config.courier.smtp.connection_uri }}
  smtpConnectionURI: {{ .Values.kratos.kratos.config.courier.smtp.connection_uri | b64enc | quote }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.db.jwtSecretKeyRef.name }}
type: Opaque
stringData:
  PGRST_JWT_SECRET: {{ $pgrstJWTSecret | quote }}
